apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-frontend
  labels:
    app: ai-frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-frontend-app
  strategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ai-frontend-app
    spec:
      containers:
        - name: open-ai-frontend
          image: <YOUR_IMAGE>
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-frontend-service
spec:
  type: ClusterIP
  selector:
    app: ai-frontend-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: default
  name: ai-frontend-ingress
spec:
  rules:
    - host: <YOUR_URL>
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ai-frontend-service
                port:
                    number: 80